### ISSUE TITLE
numpy | linalg.py |  Array must be at least two-dimensional

### ISSUE THREAD

**Issue by basai1234** [xgrau/possvm-orthology#18]
Hello, 

Thanks for this very nice software,

I have been running possum.py before with no issues. 

I wanted to re-run it couple days ago and couldn't run it anymore. I have reinstalled it, tried different python versions (on my local computer and on SLURM) and am still facing the same error. I also asked some colleagues to try independently and they also had the same issue. 

Here is the error i got from the example file:
 
```
 python possvm.py -i ./test/fa_synthases.newick  -p fa_synthases_unnamed

2023-10-17 12:41:09,170 [INFO ]	fa_synthases_unnamed num nodes = 16
2023-10-17 12:41:09,170 [INFO ]	fa_synthases_unnamed clustering function is clusters_mcl
2023-10-17 12:41:09,170 [INFO ]	fa_synthases_unnamed Midpoint root
2023-10-17 12:41:09,936 [INFO ]	Create network
2023-10-17 12:41:09,947 [INFO ]	MCL clustering, inflation = 1.500
/Users/basai/opt/miniconda3/envs/possvm/lib/python3.11/site-packages/scipy/sparse/_index.py:100: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_intXint(row, col, x.flat[0])
Traceback (most recent call last):
  File "/Users/basai/Desktop/possvm-orthology/possvm.py", line 901, in <module>
    evs, eva, phy, phy_lis, clu = parse_phylo(phy_fn=phy_fn, phy_id=phy_id, do_allpairs=do_allpairs, do_root=do_root, clusters_function_string=clusters_function_string, do_sps_reconciliation=do_sps_reconciliation)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/basai/Desktop/possvm-orthology/possvm.py", line 263, in parse_phylo
    clu = clusters_function(evs=evs, node_list=phy_lis)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/basai/Desktop/possvm-orthology/possvm.py", line 558, in clusters_mcl
    mcl_m  = markov_clustering.run_mcl(evs_m, inflation=inf)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/basai/opt/miniconda3/envs/possvm/lib/python3.11/site-packages/markov_clustering/mcl.py", line 228, in run_mcl
    matrix = iterate(matrix, expansion, inflation)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/basai/opt/miniconda3/envs/possvm/lib/python3.11/site-packages/markov_clustering/mcl.py", line 132, in iterate
    matrix = expand(matrix, expansion)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/basai/opt/miniconda3/envs/possvm/lib/python3.11/site-packages/markov_clustering/mcl.py", line 53, in expand
    return np.linalg.matrix_power(matrix, power)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/basai/opt/miniconda3/envs/possvm/lib/python3.11/site-packages/numpy/linalg/linalg.py", line 635, in matrix_power
    _assert_stacked_2d(a)
  File "/Users/basai/opt/miniconda3/envs/possvm/lib/python3.11/site-packages/numpy/linalg/linalg.py", line 206, in _assert_stacked_2d
    raise LinAlgError('%d-dimensional array given. Array must be '
numpy.linalg.LinAlgError: 0-dimensional array given. Array must be at least two-dimensional
```

It would be great if you could help us on that!

Thanks!

**Comment by xgrau** [comment]
Hi, thanks for reaching out. Can you let me know which versions of `python`, `numpy`, `scipy` and `markov_clustering` are you using?

For me, it's working with the following (from `conda list`):

```
markov_clustering         0.0.6                      py_0    bioconda
numpy                     1.23.5          py310hd5efca6_0  
python                    3.10.9               h7a1cb2a_2  
scipy                     1.10.0          py310hd5efca6_1  
```

It appears that the error comes from the `numpy` package. So, while I'm working on a fix, I'd recommend you use the version that comes with the [bundled environment](https://github.com/xgrau/possvm-orthology/blob/master/environment.yaml) (`1.23.XX`). If you can, I suggest you try reproducing this environment, as [explained here](https://github.com/xgrau/possvm-orthology#installation).

**Comment by basai1234** [comment]
Thanks for the quick response, 

I have it to run now. I found incompatibilities between numpy and scipy versions but reinstalling it with compatible version (the ones in the doc) fixed it.

I reproduced the environment as you suggested but on OS. Had to make small changes in the .yaml (see below).   

Thanks again! 

B.

```
name: base
channels:
  - bioconda/label/cf201901
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - argcomplete=3.1.2
  - argh=0.29.4
  - aria2=1.36.0
  - biopython=1.81
  - blast=2.14.1
  - boltons=23.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.20.1
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - cffi=1.16.0
  - charset-normalizer=3.3.0
  - colorama=0.4.6
  - conda=23.9.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - cryptography=41.0.4
  - curl=8.4.0
  - diamond=2.1.8
  - entrez-direct=16.2
  - fastme=2.1.6.1
  - fasttree=2.1.11
  - gawk=5.2.2
  - gettext=0.21.1
  - gffread=0.9.12
  - gffutils=0.12
  - gmp=6.2.1
  - icu=73.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - interlap=0.2.7
  - iqtree=2.2.5
  - jsonpatch=1.33
  - jsonpointer=2.4
  - k8=0.2.5
  - krb5=1.21.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.4.0
  - libcxx=16.0.6
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libnghttp2=1.52.0
  - libopenblas=0.3.24
  - libsqlite=3.43.2
  - libssh2=1.11.0
  - libunistring=0.9.10
  - libxml2=2.11.5
  - libzlib=1.2.13
  - liftoff=1.6.3
  - llvm-openmp=17.0.2
  - mafft=7.520
  - mcl=22.282
  - minimap2=2.26
  - mmseqs2=14.7e284
  - mpfr=4.2.0
  - mpi=1.0
  - muscle=5.1
  - ncbi-vdb=3.0.0
  - ncurses=6.4
  - networkx=3.1
  - openmpi=4.1.6
  - openssl=3.1.3
  - orthofinder=2.5.4
  - packaging=23.2
  - parasail-python=1.3.4
  - pcre=8.45
  - perl=5.32.1
  - perl-archive-tar=2.40
  - perl-carp=1.50
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.201
  - perl-compress-raw-zlib=2.202
  - perl-encode=3.19
  - perl-exporter=5.74
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-io-compress=2.201
  - perl-io-zlib=1.14
  - perl-json=4.10
  - perl-json-xs=2.34
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-parent=0.241
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.63
  - perl-storable=3.15
  - perl-types-serialiser=1.01
  - pip=23.3
  - pluggy=1.3.0
  - pycosat=0.6.6
  - pycparser=2.21
  - pyfaidx=0.7.2.2
  - pyopenssl=23.2.0
  - pysam=0.21.0
  - pysocks=1.7.1
  - python=3.9.18
  - python.app=3
  - python_abi=3.9
  - pyvcf3=1.0.3
  - raxml=8.2.13
  - raxml-ng=1.2.0
  - readline=8.2
  - requests=2.31.0
  - ruamel.yaml=0.17.35
  - ruamel.yaml.clib=0.2.7
  - scipy=1.10.0
  - setuptools=68.2.2
  - simplejson=3.19.2
  - six=1.16.0
  - tk=8.6.13
  - tqdm=4.66.1
  - tzdata=2023c
  - ujson=5.8.0
  - urllib3=2.0.6
  - wget=1.20.3
  - wheel=0.41.2
  - xz=5.2.6
  - zipp=3.17.0
  - zlib=1.2.13
  - zstandard=0.21.0
  - zstd=1.5.5
  - pip:
      - networkx==3.0
      - markov_clustering==0.0.6.dev0
      - ete3==3.1.2
      - numpy==1.21.4
      - pandas==1.3.4
      - python-dateutil==2.8.2
      - pytz==2021.3
prefix: /Users/basai/opt/miniconda3

```
